### ISSUE TITLE
If there's an IP address, geolocate it and add it as a geo_point-type field in elasticsearch (so we can query on maps)

### ISSUE THREAD

**Issue by marten** [zooniverse/zoo-event-stats#2]

**Comment by camallen** [comment]
@marten this is fixed right?

**Comment by marten** [comment]
Not entirely, ES picked `double` as a field type before I managed to set it as `geo_point`, so now I still have to reindex all docs into a new index with the correct mapping. I messed up my last reindex attempt, and not enough time to do another today, so next thing tomorrow.

**Comment by camallen** [comment]
cool. we still need to replay old data into es too.

**Comment by camallen** [comment]
did this get sorted with the new index?

**Comment by marten** [comment]
Yep
